In [7]:
#generates magic squares of any odd size
import numpy as np

def set_matrix(n):
    matrix = np.random.randint(0,1,(n,n))*0
    matrix_list = np.arange(1,n+1,1,int)
    x = n-1
    y = int(np.median(matrix_list))-1
    matrix[x,y] = 1
    for value in range(2,n*n+1):
        if value % n != 1:
            x = (x + 1) % n
            y = (y + 1) % n
            matrix[x,y] = value
        elif value % n == 1:
            x = x - 1
            y = y
            matrix[x,y] = value
    return matrix

def matrix_sum(n):
    matrix_sum = int(((n**3) + n) / 2)
    return matrix_sum

def result(n):
    print(set_matrix(n))
    print(f"\nthe magic square sum is " + str(matrix_sum(n)))

n = int(input("enter magic square size (odd number):"))
print("\n")
result(n)

enter magic square size (odd number):11


[[ 56  69  82  95 108 121   2  15  28  41  54]
 [ 55  57  70  83  96 109 111   3  16  29  42]
 [ 43  45  58  71  84  97 110 112   4  17  30]
 [ 31  44  46  59  72  85  98 100 113   5  18]
 [ 19  32  34  47  60  73  86  99 101 114   6]
 [  7  20  33  35  48  61  74  87  89 102 115]
 [116   8  21  23  36  49  62  75  88  90 103]
 [104 117   9  22  24  37  50  63  76  78  91]
 [ 92 105 118  10  12  25  38  51  64  77  79]
 [ 80  93 106 119  11  13  26  39  52  65  67]
 [ 68  81  94 107 120   1  14  27  40  53  66]]

the magic square sum is 671
