In [1]:
#make it work for any size s squares

import numpy as np

#input the s length square and transform it into a s*s length list
magic_square = np.matrix([[4,3,8],
                          [9,5,1],
                          [2,7,6]])
print(magic_square)

magic_list = np.array(magic_square).flatten().tolist()
size = len(magic_square)
# enter a validation here to ensure a s by s matrix

#validate the sum of rows, sum of columns, sum of diagonals:
class square():

    def row_sum():
#check the sum of rows by selectinng every s block of list elements and validating their sum against the prior block
        start = 0
        end = size
        for i in range(size-1):
            prev_row_sum = np.sum(magic_list[start:end])
            start += size
            end += size
            row_sum = np.sum(magic_list[start:end])
            if prev_row_sum == row_sum:
                row_sum = row_sum     
            else:
                row_sum = 0
                break
        return row_sum

    def col_sum():
#the matrix columns are identified as sublists of elements: [1, 1+s, 1+2s,..., 1+(s-1)s], [2, 2+s, 2+2s,..., 2+(s-1)s],...,[s, s+s, s+2s....s+(s-1)s]. The sum of the sublist elements is compared one by one with the row_sum.
        start = 0
        step = size
        for i in range(size):
            col_sum = np.sum(magic_list[start::step])
            start += 1
            if square.row_sum() == col_sum:
                col_sum = col_sum
            else:
                col_sum = 0
                break
        return col_sum
            

    def diag_sum(list):
#the left-to-right diagonal is the same as the right-to-left diagonal of the reversed list, thus the same algorithm cam be used for 
        step = 0
        diag_sum = 0
        for i in range(1,size+1):
            diag_sum += list[step]
            step = i * (size + 1)
        return diag_sum

#written in separate blocks, so that if any validation fails, the others are not run:
    def check():
        magic_list_reversed = magic_list[::-1]
        if square.row_sum() == 0:
            return False
        elif square.col_sum() == 0:
            return False
        elif square.col_sum() == square.diag_sum(magic_list) == square.diag_sum(magic_list_reversed):
            return True
        else:
            return False
            
if square.check():
    print(f"This is a magic square of sum " + str(square.row_sum()) + "!")
else:
    print(f"This is not a magic square!")

[[4 3 8]
 [9 5 1]
 [2 7 6]]
This is a magic square of sum 15!
